### PR TITLE
Adjusting CLIFlow and Desierializer to use 'StartsWith' instead of 'Con…

### PR DESCRIPTION
**Pull request by MarcinIN**
…tains'

### CODE REVIEW

**Review by xHoody — APPROVED** [review]
Changes are fine for me - nothing to be corrected

**Comment by jmarlew** [comment]
"StartWith"?

**Comment by jmarlew** [comment]
I don't get the context of this issue.
So commands and options may contain a hyphen, but it should be max one in a row? ie. accept `coco-nut` or `co-co-nut` but reject `coco--nut`?

**Comment by MarcinIN** [comment]
@jmarlew take a look at the tests:
command that would contains `-` would be treated as option.. So in theory you would like to have commands: `get-logs`, `display-logs` and let's assume that `display-logs` was set as default.

Now:  if you would run: `get-logs --all` - you would get an exception because `get-logs` would be treated as on option for default command. Hope that makes sense.

**Comment by MarcinIN** [comment]
After thinking about it - I will merge it and release 2.0.1 - because major problem is fixed and than open an issue to introduce changes proposed by @jmarlew  in 2.1.

**Pull request merged**
